-- Minimal replica of the EF-generated tables that stock_integrity.sql touches
-- (column names/types taken from WmsDbContextModelSnapshot.cs). Used only by
-- tests, so the SQL layer can be verified without the .NET toolchain.
CREATE TABLE "Stocks" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ProductId" integer NOT NULL, "WarehouseId" integer NOT NULL, "LocationId" integer NULL,
  "Quantity" numeric(18,3) NOT NULL, "ReservedQuantity" numeric(18,3) NOT NULL,
  "AverageCost" numeric(18,2) NOT NULL, "ReorderPoint" numeric(18,3) NOT NULL,
  "LastUpdated" timestamptz NOT NULL);
CREATE UNIQUE INDEX "IX_Stocks_ProductId_WarehouseId_LocationId" ON "Stocks" ("ProductId","WarehouseId","LocationId");
CREATE TABLE "StockMovements" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "StockId" integer NOT NULL REFERENCES "Stocks"("Id"),
  "Type" integer NOT NULL, "Quantity" numeric(18,3) NOT NULL, "UnitCost" numeric(18,2) NOT NULL,
  "Reference" text, "Notes" text, "CreatedAt" timestamptz NOT NULL);
CREATE TABLE "Lots" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "StockId" integer NOT NULL REFERENCES "Stocks"("Id"),
  "LotNumber" varchar(100) NOT NULL, "Quantity" numeric(18,3) NOT NULL, "CreatedAt" timestamptz NOT NULL);
CREATE TABLE "Orders" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "OrderNumber" varchar(50) NOT NULL UNIQUE, "Status" integer NOT NULL,
  "OrderDate" timestamptz NOT NULL, "ShippedDate" timestamptz NULL);
CREATE TABLE "OrderItems" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "OrderId" integer NOT NULL REFERENCES "Orders"("Id"), "ProductId" integer NOT NULL, "WarehouseId" integer NOT NULL DEFAULT 1,
  "Quantity" numeric(18,3) NOT NULL);
CREATE TABLE "Invoices" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "InvoiceNumber" varchar(50) NOT NULL UNIQUE);

CREATE TABLE "IdempotencyKeys" (
  "Key" text PRIMARY KEY,
  "Scope" text,
  "ResourceId" int,
  "CreatedAt" timestamptz,
  "RequestHash" text);
