-- ============================================================================
-- WMS reservations and partial shipments  (applied after stock_integrity.sql)
--
-- Adds, INSIDE the database:
--   * order reservations: an order can hold units, nobody else can issue them
--   * partial shipments: an order line can be shipped in several steps
--   * status PartiallyShipped (6) until every line is complete, then Shipped (3)
--
-- Invariants (checked by tests/db/test_reservations.py and the views below):
--   1. Stocks.ReservedQuantity == SUM(OrderItemReservations.Quantity) per stock
--   2. OrderItems.ShippedQuantity <= OrderItems.Quantity
--   3. reserved + shipped for a line never exceeds the line quantity
--
-- SQLSTATEs added (the API maps them to HTTP errors):
--   WMS05 order not in a state that allows this      WMS06 shipping more than remains on the line
--   WMS07 stock row belongs to another product       WMS08 cannot cancel: units already shipped
--   (WMS01 insufficient stock is reused for reservations)
--
-- Order status ints: 0 Pending, 1 Confirmed, 2 Processing, 3 Shipped, 4 Delivered, 5 Cancelled, 6 PartiallyShipped
-- Idempotent: safe to run twice.
-- ============================================================================

ALTER TABLE "OrderItems" ADD COLUMN IF NOT EXISTS "ShippedQuantity" numeric(18,3) NOT NULL DEFAULT 0;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_orderitems_shipped_range') THEN
    ALTER TABLE "OrderItems" ADD CONSTRAINT ck_orderitems_shipped_range
      CHECK ("ShippedQuantity" >= 0 AND "ShippedQuantity" <= "Quantity");
  END IF;
END $$;

-- Orders shipped before this migration were shipped in full.
UPDATE "OrderItems" oi SET "ShippedQuantity" = oi."Quantity"
  FROM "Orders" o
 WHERE o."Id" = oi."OrderId" AND o."Status" IN (3,4) AND oi."ShippedQuantity" = 0;

CREATE TABLE IF NOT EXISTS "OrderItemReservations" (
    "Id"          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OrderItemId" integer       NOT NULL REFERENCES "OrderItems"("Id") ON DELETE CASCADE,
    "StockId"     integer       NOT NULL REFERENCES "Stocks"("Id"),
    "Quantity"    numeric(18,3) NOT NULL CHECK ("Quantity" > 0),
    "CreatedAt"   timestamptz   NOT NULL DEFAULT now(),
    CONSTRAINT ux_reservation_item_stock UNIQUE ("OrderItemId","StockId")
);
CREATE INDEX IF NOT EXISTS ix_reservations_stock ON "OrderItemReservations" ("StockId");

-- ---------------------------------------------------------------------------
-- Reserve every open line of an order, all or nothing.
-- Lines are processed by (ProductId, WarehouseId, Id) and stock rows are locked in Id order, so
-- two orders reserving at the same time cannot deadlock. If any line cannot be covered the
-- function raises WMS01 and the caller's transaction undoes the lines already reserved.
-- Returns the quantity newly reserved. Calling it again only tops up what is still missing.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION wms_order_reserve(p_order_id int) RETURNS numeric
LANGUAGE plpgsql AS $$
DECLARE
  v_status int; it record; st record;
  v_need numeric; v_take numeric; v_total numeric := 0; v_have numeric;
BEGIN
  SELECT "Status" INTO v_status FROM "Orders" WHERE "Id" = p_order_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION USING ERRCODE = 'WMS05', MESSAGE = format('order %s not found', p_order_id);
  END IF;
  IF v_status NOT IN (0,1,2,6) THEN
    RAISE EXCEPTION USING ERRCODE = 'WMS05', MESSAGE = 'order cannot be reserved in its current status';
  END IF;

  FOR it IN
    SELECT "Id","ProductId","WarehouseId","Quantity","ShippedQuantity"
      FROM "OrderItems" WHERE "OrderId" = p_order_id
     ORDER BY "ProductId","WarehouseId","Id"
  LOOP
    SELECT COALESCE(SUM("Quantity"),0) INTO v_have FROM "OrderItemReservations" WHERE "OrderItemId" = it."Id";
    v_need := it."Quantity" - it."ShippedQuantity" - v_have;
    CONTINUE WHEN v_need <= 0;

    FOR st IN
      SELECT "Id","Quantity","ReservedQuantity" FROM "Stocks"
       WHERE "ProductId" = it."ProductId" AND "WarehouseId" = it."WarehouseId"
       ORDER BY "Id" FOR UPDATE
    LOOP
      EXIT WHEN v_need <= 0;
      v_take := LEAST(v_need, st."Quantity" - st."ReservedQuantity");
      CONTINUE WHEN v_take <= 0;

      UPDATE "Stocks" SET "ReservedQuantity" = "ReservedQuantity" + v_take, "LastUpdated" = now()
       WHERE "Id" = st."Id";
      INSERT INTO "OrderItemReservations"("OrderItemId","StockId","Quantity")
      VALUES (it."Id", st."Id", v_take)
      ON CONFLICT ("OrderItemId","StockId")
        DO UPDATE SET "Quantity" = "OrderItemReservations"."Quantity" + EXCLUDED."Quantity";
      v_need  := v_need - v_take;
      v_total := v_total + v_take;
    END LOOP;

    IF v_need > 0 THEN
      RAISE EXCEPTION USING ERRCODE = 'WMS01', MESSAGE = 'insufficient stock',
        DETAIL = format('{"stockId":0,"productId":%s,"required":%s,"available":%s}',
                        it."ProductId", it."Quantity" - it."ShippedQuantity", it."Quantity" - it."ShippedQuantity" - v_need);
    END IF;
  END LOOP;

  RETURN v_total;
END $$;

-- Give back every unit the order still holds. Idempotent.
CREATE OR REPLACE FUNCTION wms_order_release(p_order_id int) RETURNS numeric
LANGUAGE plpgsql AS $$
DECLARE r record; v_total numeric := 0;
BEGIN
  FOR r IN
    SELECT res."Id", res."StockId", res."Quantity"
      FROM "OrderItemReservations" res
      JOIN "OrderItems" oi ON oi."Id" = res."OrderItemId"
     WHERE oi."OrderId" = p_order_id
     ORDER BY res."StockId", res."Id"
  LOOP
    UPDATE "Stocks" SET "ReservedQuantity" = "ReservedQuantity" - r."Quantity", "LastUpdated" = now()
     WHERE "Id" = r."StockId";
    DELETE FROM "OrderItemReservations" WHERE "Id" = r."Id";
    v_total := v_total + r."Quantity";
  END LOOP;
  RETURN v_total;
END $$;

-- ---------------------------------------------------------------------------
-- Ship p_qty of one order line from one stock row. Returns the order status after the shipment
-- (6 PartiallyShipped or 3 Shipped). The order row is locked first, so concurrent shipments of the
-- same order are serialized and only one of them can be the one that completes it.
-- Units this order reserved on that stock are consumed first; any extra comes from free stock.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION wms_order_ship_line(
    p_order_item_id int, p_stock_id int, p_qty numeric, p_ref text)
RETURNS int
LANGUAGE plpgsql AS $$
DECLARE
  v_order int; v_status int; v_qty numeric; v_shipped numeric; v_product int;
  v_stock_product int; v_res numeric; v_consume numeric; v_open int; v_new_status int;
BEGIN
  IF p_qty IS NULL OR p_qty <= 0 THEN
    RAISE EXCEPTION USING ERRCODE = 'WMS02', MESSAGE = 'quantity must be greater than 0';
  END IF;

  SELECT "OrderId" INTO v_order FROM "OrderItems" WHERE "Id" = p_order_item_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION USING ERRCODE = 'WMS05', MESSAGE = format('order line %s not found', p_order_item_id);
  END IF;

  SELECT "Status" INTO v_status FROM "Orders" WHERE "Id" = v_order FOR UPDATE;
  IF v_status NOT IN (0,1,2,6) THEN
    RAISE EXCEPTION USING ERRCODE = 'WMS05', MESSAGE = 'order is already shipped or cancelled';
  END IF;

  SELECT "Quantity","ShippedQuantity","ProductId" INTO v_qty, v_shipped, v_product
    FROM "OrderItems" WHERE "Id" = p_order_item_id FOR UPDATE;
  IF p_qty > v_qty - v_shipped THEN
    RAISE EXCEPTION USING ERRCODE = 'WMS06',
      MESSAGE = format('cannot ship %s: only %s remain on this line', p_qty, v_qty - v_shipped);
  END IF;

  SELECT "ProductId" INTO v_stock_product FROM "Stocks" WHERE "Id" = p_stock_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION USING ERRCODE = 'WMS03', MESSAGE = format('stock %s not found', p_stock_id);
  END IF;
  IF v_stock_product <> v_product THEN
    RAISE EXCEPTION USING ERRCODE = 'WMS07', MESSAGE = 'stock row belongs to another product';
  END IF;

  -- consume this line's reservation on that stock first
  SELECT COALESCE(SUM("Quantity"),0) INTO v_res FROM "OrderItemReservations"
   WHERE "OrderItemId" = p_order_item_id AND "StockId" = p_stock_id;
  v_consume := LEAST(v_res, p_qty);
  IF v_consume > 0 THEN
    UPDATE "Stocks" SET "ReservedQuantity" = "ReservedQuantity" - v_consume WHERE "Id" = p_stock_id;
    IF v_res - v_consume > 0 THEN
      UPDATE "OrderItemReservations" SET "Quantity" = "Quantity" - v_consume
       WHERE "OrderItemId" = p_order_item_id AND "StockId" = p_stock_id;
    ELSE
      DELETE FROM "OrderItemReservations" WHERE "OrderItemId" = p_order_item_id AND "StockId" = p_stock_id;
    END IF;
  END IF;

  PERFORM wms_stock_issue(p_stock_id, p_qty, 1, p_ref, 'Shipment - ' || COALESCE(p_ref,''));

  UPDATE "OrderItems" SET "ShippedQuantity" = "ShippedQuantity" + p_qty WHERE "Id" = p_order_item_id;

  SELECT COUNT(*) INTO v_open FROM "OrderItems"
   WHERE "OrderId" = v_order AND "ShippedQuantity" < "Quantity";
  v_new_status := CASE WHEN v_open = 0 THEN 3 ELSE 6 END;

  UPDATE "Orders"
     SET "Status" = v_new_status,
         "ShippedDate" = CASE WHEN v_new_status = 3 THEN now() ELSE "ShippedDate" END
   WHERE "Id" = v_order;

  IF v_new_status = 3 THEN
    PERFORM wms_order_release(v_order);   -- nothing should remain; belt and braces
  END IF;

  RETURN v_new_status;
END $$;

-- Cancel an order that has not shipped anything; its reservations go back to free stock.
CREATE OR REPLACE FUNCTION wms_order_cancel(p_order_id int) RETURNS void
LANGUAGE plpgsql AS $$
DECLARE v_status int; v_shipped numeric;
BEGIN
  SELECT "Status" INTO v_status FROM "Orders" WHERE "Id" = p_order_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION USING ERRCODE = 'WMS05', MESSAGE = format('order %s not found', p_order_id);
  END IF;
  IF v_status = 5 THEN RETURN; END IF;
  IF v_status NOT IN (0,1,2,6) THEN
    RAISE EXCEPTION USING ERRCODE = 'WMS05', MESSAGE = 'order cannot be cancelled in its current status';
  END IF;
  SELECT COALESCE(SUM("ShippedQuantity"),0) INTO v_shipped FROM "OrderItems" WHERE "OrderId" = p_order_id;
  IF v_shipped > 0 THEN
    RAISE EXCEPTION USING ERRCODE = 'WMS08', MESSAGE = 'cannot cancel: units have already shipped';
  END IF;
  PERFORM wms_order_release(p_order_id);
  UPDATE "Orders" SET "Status" = 5 WHERE "Id" = p_order_id;
END $$;

-- Rows here are BUGS: Stocks.ReservedQuantity must equal the sum of the reservations. Always empty.
CREATE OR REPLACE VIEW wms_reservation_drift AS
SELECT COALESCE(s."Id", r."StockId") AS stock_id,
       COALESCE(s."ReservedQuantity", 0) AS stock_reserved,
       COALESCE(r.total, 0)              AS reservations_total
  FROM "Stocks" s
  FULL JOIN (SELECT "StockId", SUM("Quantity") AS total FROM "OrderItemReservations" GROUP BY "StockId") r
         ON r."StockId" = s."Id"
 WHERE COALESCE(s."ReservedQuantity", 0) <> COALESCE(r.total, 0);
