-- Minimal replica of the EF tables the analytics service reads (names/types from the EF snapshot).
CREATE TABLE "Products" ("Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Code" text NOT NULL,
  "Name" text NOT NULL, "CostPrice" numeric(18,2) NOT NULL DEFAULT 0);
CREATE TABLE "Stocks" ("Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "ProductId" integer NOT NULL,
  "WarehouseId" integer NOT NULL DEFAULT 1, "LocationId" integer, "Quantity" numeric(18,3) NOT NULL,
  "ReservedQuantity" numeric(18,3) NOT NULL DEFAULT 0, "AverageCost" numeric(18,4) NOT NULL DEFAULT 0,
  "ReorderPoint" numeric(18,3) NOT NULL DEFAULT 0, "LastUpdated" timestamptz NOT NULL DEFAULT now());
CREATE TABLE "Orders" ("Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "OrderNumber" text NOT NULL,
  "Status" integer NOT NULL DEFAULT 0, "OrderDate" timestamptz NOT NULL, "TotalAmount" numeric(18,2) NOT NULL DEFAULT 0);
CREATE TABLE "OrderItems" ("Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "OrderId" integer NOT NULL REFERENCES "Orders"("Id"), "ProductId" integer NOT NULL, "Quantity" numeric(18,3) NOT NULL);
CREATE INDEX ix_orders_orderdate ON "Orders" ("OrderDate");
CREATE INDEX ix_orderitems_product_order ON "OrderItems" ("ProductId","OrderId");

-- same covering index as backend-csharp/WMS.Data/Sql/analytics_indexes.sql
CREATE INDEX IF NOT EXISTS ix_orders_id_cover ON "Orders" ("Id") INCLUDE ("OrderDate","Status");
